services:
  vm:
    image: ssst0n3/docker_archive:podman-v5.5.1_v0.1.0
    # Use host cpu to fix: "Fatal glibc error: CPU does not support x86-64-v2"
    command: /start.sh -cpu host
    ports:
        - "55100:22"
    tty: true
    stdin_open: true 
