services:
  vm:
    image: ssst0n3/docker_archive:docker-v28.0.4_centos-stream9_v0.1.0
    # Use host cpu to fix: "Fatal glibc error: CPU does not support x86-64-v2"
    command: /start.sh -cpu host    
    ports:
        - "28049:22"
    tty: true
    stdin_open: true 