services:
  vm:
    image: ssst0n3/docker_archive:docker-v19.03.13-debug_v0.1.0
    environment:
        - "QEMU_HOSTFWD=hostfwd=tcp::2341-:2341,hostfwd=tcp::2342-:2342,hostfwd=tcp::2343-:2343,hostfwd=tcp::2344-:2344,hostfwd=tcp::2345-:2345,hostfwd=tcp::2346-:2346,hostfwd=tcp::2347-:2347,hostfwd=tcp::2348-:2348,hostfwd=tcp::2349-:2349"
    ports:
        - "19310:22"
        - "19311:2341" # runc main
        - "19312:2342" # runc init
        - "19313:2343" # dockerd 
        - "19314:2344" # docker; not avaiable now, preservce
        - "19315:2345" # containerd
        - "19316:2346" # containerd-shim
        - "19317:2347" # containerd-shim-runc-v1
        - "19328:2348" # containerd-shim-runc-v2
        - "19329:2349" # ctr
    tty: true
    stdin_open: true 
