version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:ubuntu-22.04_runc-1.1.4_v0.1.0
    ports:
      - "1140:22"
    command: /start_vm.sh -enable-kvm
    devices:
      - "/dev/kvm:/dev/kvm"
    tty: true
    stdin_open: true
