version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:ubuntu-20.04_kubernetes-1.23.4_containerd.io-1.5.9_calico-3.22.1_istio-1.13.0
    tty: true
    stdin_open: true
    ports:
        - "2222:22"
