version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:ubuntu-16.04_kubeadm-1.9.4_kubelet-1.9.4_kubectl-1.9.4_kubernetes-cni-0.6.0_flannel-0.9.1_docker-ce-17.03.3
    tty: true
    stdin_open: true
    ports:
        - "2222:22"
