version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:ubuntu-20.04_docker-ce-17.06.0_v0.1.0
    ports:
        - "17060:22"
        - "2345:2345"
        - "2346:2346"
    command: qemu-system-x86_64 -hda ubuntu-server-cloudimg.img -net nic -net user,hostfwd=tcp::22-:22,hostfwd=tcp::2345-:2345,hostfwd=tcp::2346-:2346 -smp 2 -m 2048M -nographic -enable-kvm
    devices:
      - "/dev/kvm:/dev/kvm"
    tty: true
    stdin_open: true
