version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:ubuntu-20.04_docker-ce-20.10.0-beta1_containerd.io-1.6.25_runc-1.1.10_v0.1.0
    ports:
        - "20101:22"
    tty: true
    stdin_open: true 
