services:
  vm:
    image: ssst0n3/docker_archive:docker-v28.0.4_centos-stream9_runc-v1.2.5-debug_v0.1.0
    # Use host cpu to fix: "Fatal glibc error: CPU does not support x86-64-v2"
    command: /start.sh -cpu host    
    environment:
        - "QEMU_HOSTFWD=hostfwd=tcp::2346-:2346,hostfwd=tcp::2347-:2347"
    ports:
        - "28042:22"
        - "28046:2346"
        - "28047:2347"
    tty: true
    stdin_open: true 