version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:runc-v1.0.0-rc2-dbg_v0.1.0
    ports:
        - "10021:22"
        - "10022:2345"
        - "10023:2346"
    environment:
      - "QEMU_HOSTFWD=hostfwd=tcp::2345-:2345,hostfwd=tcp::2346-:2346"
    tty: true
    stdin_open: true 