version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:ubuntu-22.04-dbg_v0.2.0
    ports:
        - "22041:22"
    command: /start.sh -kernel /vmlinux -append 'root=/dev/sda1 net.ifnames=0 console=tty0 console=ttyS0,115200n8 nokalsr' -s -S -smp 1
    tty: true
    stdin_open: true 
