version: '3'
services:
  vm:
    image: ssst0n3/docker_archive:runc-v1.0.0-rc3-dbg_v0.1.0
    ports:
        - "10031:22"
        - "10032:2345"
        - "10033:2346"
    tty: true
    stdin_open: true 