services:
  master:
    image: ssst0n3/docker_archive:cve-2020-8558-master_v0.1.0
    environment:
      - "QEMU_HOSTFWD=hostfwd=tcp::6443-:6443"
      - "QEMU_DUAL_NET=1"
      - "QEMU_SOCKET_LISTEN=:1234"
      - "QEMU_SOCKET_IP=10.0.2.16"
      - "QEMU_MAC_ADDR_0=52:54:00:12:34:56"
      - "QEMU_MAC_ADDR_1=52:54:00:12:34:57"
    ports:
        - "28558:22"
        - "38558:6443"
    tty: true
    stdin_open: true 
    healthcheck:
      test: ["CMD-SHELL", "pgrep qemu-system-x86_64"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 60s
  worker:
    depends_on: 
      master:
        # wait master's qemu listen on :1234
        condition: service_healthy
    image: ssst0n3/docker_archive:cve-2020-8558-worker_v0.1.0
    environment:
      - "QEMU_DUAL_NET=1"
      - "QEMU_SOCKET_CONNECT=master:1234"
      - "QEMU_SOCKET_IP=10.0.2.17"
      - "QEMU_MAC_ADDR_0=52:54:00:12:34:58"
      - "QEMU_MAC_ADDR_1=52:54:00:12:34:59"
    ports:
        - "48558:22"
    tty: true
    stdin_open: true 
